# pg_hba.conf - CUSTOMIZED FOR IA MEDIA PROJECT
# File này sẽ được copy lên server để cấu hình quyền truy cập PostgreSQL

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
# Giữ nguyên các dòng mặc định để đảm bảo các kết nối nội bộ hoạt động
local   all             all                                     trust

# IPv4 local connections:
host    all             all             127.0.0.1/32            md5

# IPv6 local connections:
host    all             all             ::1/128                 md5

# Cho phép kết nối từ bất kỳ mạng nội bộ nào của Docker.
# An toàn vì container không expose ra internet.
host    all             all             172.16.0.0/12           md5
host    all             all             192.168.0.0/16          md5